name: Deploy Odoo to Server

on:
  push:
    branches: [ main ]  # Trigger saat push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Files to Server
        run: |
          scp -o StrictHostKeyChecking=no -r . ubuntu@15.235.163.201:/home/ubuntu/odoo-deploy

      - name: Restart Containers
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.235.163.201 "
            cd /home/ubuntu/odoo-deploy &&
            docker compose down &&
            docker compose pull &&
            docker compose up -d
          "
